/* parser generated by jison 0.4.15 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,6],$V1=[1,8],$V2=[8,12],$V3=[6,14,17],$V4=[1,21],$V5=[1,20],$V6=[1,28],$V7=[6,14,17,21,23],$V8=[14,17],$V9=[1,37],$Va=[14,16,17,23,30,37,38,39,40,41,42,43],$Vb=[1,38],$Vc=[1,45],$Vd=[1,49],$Ve=[1,50],$Vf=[1,46],$Vg=[1,60],$Vh=[1,61],$Vi=[1,66],$Vj=[1,64],$Vk=[1,65],$Vl=[1,67],$Vm=[1,68],$Vn=[1,69],$Vo=[1,70],$Vp=[1,71],$Vq=[14,16,17,37,38,39,40,41,42,43],$Vr=[1,74],$Vs=[14,16,17,23,28,30,37,38,39,40,41,42,43],$Vt=[17,23],$Vu=[11,15,28,34],$Vv=[2,25];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"template":3,"import_list":4,"template_def":5,"EOF":6,"import":7,"IMPORT":8,"import_identifier":9,"FROM":10,"STRING":11,"{":12,"import_identifier_list":13,"}":14,"IDENTIFIER":15,"*":16,",":17,"block_with_actions":18,"block":19,"property_list":20,"(":21,"action_list":22,")":23,"property":24,":":25,"property_value":26,"accessor":27,"[":28,"]":29,".":30,"value":31,"operation_list":32,"binding":33,"NUMBER":34,"operation":35,"operator":36,"+":37,"-":38,"\\":39,"==":40,">=":41,"<=":42,"!=":43,"action":44,"action_parameter_list":45,"action_parameter":46,"$accept":0,"$end":1},
terminals_: {2:"error",6:"EOF",8:"IMPORT",10:"FROM",11:"STRING",12:"{",14:"}",15:"IDENTIFIER",16:"*",17:",",21:"(",23:")",25:":",28:"[",29:"]",30:".",34:"NUMBER",37:"+",38:"-",39:"\\",40:"==",41:">=",42:"<=",43:"!="},
productions_: [0,[3,3],[3,2],[7,4],[7,6],[4,1],[4,2],[9,1],[9,1],[13,1],[13,3],[5,1],[19,3],[19,2],[18,1],[18,4],[24,3],[24,3],[24,3],[24,3],[24,1],[20,1],[20,3],[27,1],[27,3],[27,3],[27,4],[26,1],[26,1],[31,1],[31,1],[31,1],[32,1],[32,3],[35,3],[36,1],[36,1],[36,1],[36,1],[36,1],[36,1],[36,1],[36,1],[33,1],[33,3],[44,3],[44,4],[22,1],[22,3],[46,1],[46,1],[46,1],[46,1],[45,1],[45,3]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

      $$[$0-1].imports = $$[$0-2];
      return $$[$0-1];
    
break;
case 2:
 return $$[$0-1]; 
break;
case 3:
 
      this.$ = new yy.ImportNode(_$[$0-3].first_line, _$[$0-3].first_column, $$[$0-2], $$[$0]);
    
break;
case 4:

      var imports = [];
      $$[$0-3].forEach(function(ident) {
        imports.push(new yy.ImportNode(_$[$0-5].first_line, _$[$0-5].first_column, ident, $$[$0]));
      });

      this.$ = imports;
    
break;
case 5: case 9: case 21: case 47: case 53:

      if ( !Array.isArray($$[$0]) ) {
        this.$ = [ $$[$0] ];
      }
    
break;
case 6:

      this.$ = $$[$0-1].concat($$[$0]);
    
break;
case 10: case 22: case 48: case 54:

      this.$ = $$[$0-2].concat($$[$0]);
    
break;
case 11:

      this.$ = new yy.TemplateNode(_$[$0].first_line, _$[$0].first_column, $$[$0]);
    
break;
case 12:

      this.$ = new yy.BlockNode(_$[$0-2].first_line, _$[$0-2].first_column, $$[$0-1]);
    
break;
case 13:

      this.$ = new yy.BlockNode(_$[$0-1].first_line, _$[$0-1].first_column, []);
    
break;
case 15:

      this.$ = $$[$0-3];
      this.$.actions = $$[$0-1];
    
break;
case 16: case 17: case 18: case 19:

      this.$ = new yy.PropertyNode(_$[$0-2].first_line, _$[$0-2].first_column, $$[$0-2], $$[$0]);
    
break;
case 20:

      var value = new yy.ValueNode(_$[$0].first_line, _$[$0].first_column, new yy.AccessorNode(_$[$0].first_line, _$[$0].first_column, $$[$0]));
      this.$ = new yy.PropertyNode(_$[$0].first_line, _$[$0].first_column, $$[$0], value);
    
break;
case 23:

      this.$ = new yy.AccessorNode(_$[$0].first_line, _$[$0].first_column, $$[$0]);
    
break;
case 24:

      this.$ = new yy.AccessorNode(_$[$0-2].first_line, _$[$0-2].first_column, $$[$0-1]);
    
break;
case 25:

      $$[$0-2].addProperty($$[$0]);
    
break;
case 26:

      $$[$0-3].addProperty($$[$0-1]);
    
break;
case 29: case 30: case 50:

      this.$ = new yy.ValueNode(_$[$0].first_line, _$[$0].first_column, $$[$0]);
    
break;
case 31: case 51:

      this.$ = new yy.ValueNode(_$[$0].first_line, _$[$0].first_column, parseInt($$[$0]));
    
break;
case 33: case 34:
 this.$ = new yy.OperatorNode(_$[$0-2].first_line, _$[$0-2].first_column, $$[$0-2], $$[$0], $$[$0-1]); 
break;
case 44:

      this.$ = $$[$0-2];
      this.$.actions = $$[$0];
    
break;
case 45:
 
      this.$ = new yy.ActionNode(_$[$0-2].first_line, _$[$0-2].first_column, $$[$0-2]);
    
break;
case 46:

      this.$ = new yy.ActionNode(_$[$0-3].first_line, _$[$0-3].first_column, $$[$0-3], $$[$0-1]);
    
break;
}
},
table: [{3:1,4:2,5:3,7:4,8:$V0,12:$V1,18:5,19:7},{1:[3]},{5:9,7:10,8:$V0,12:$V1,18:5,19:7},{6:[1,11]},o($V2,[2,5]),{6:[2,11]},{9:12,12:[1,13],15:[1,14],16:[1,15]},o($V3,[2,14],{21:[1,16]}),{11:$V4,14:[1,18],15:$V5,20:17,24:19},{6:[1,22]},o($V2,[2,6]),{1:[2,2]},{10:[1,23]},{13:24,15:[1,25]},{10:[2,7]},{10:[2,8]},{15:$V6,22:26,44:27},{14:[1,29],17:[1,30]},o($V7,[2,13]),o($V8,[2,21]),o($V8,[2,20],{25:[1,31]}),{25:[1,32]},{1:[2,1]},{11:[1,33]},{14:[1,34],17:[1,35]},o($V8,[2,9]),{23:[1,36],30:$V9},o($Va,[2,47]),{21:$Vb},o($V7,[2,12]),{11:$V4,15:$V5,24:39},{11:$Vc,12:$V1,15:$Vd,18:41,19:7,26:40,27:48,28:$Ve,31:42,32:43,33:44,34:$Vf,35:47},{11:$Vc,12:$V1,15:$Vd,18:52,19:7,26:51,27:48,28:$Ve,31:42,32:43,33:44,34:$Vf,35:47},o($V2,[2,3]),{10:[1,53]},{15:[1,54]},o($V3,[2,15]),{15:$V6,44:55},{11:$Vg,12:$V1,15:$Vd,19:62,23:[1,56],27:59,28:$Ve,34:$Vh,45:57,46:58},o($V8,[2,22]),o($V8,[2,16]),o($V8,[2,18]),o($V8,[2,27],{36:63,16:$Vi,37:$Vj,38:$Vk,39:$Vl,40:$Vm,41:$Vn,42:$Vo,43:$Vp}),o($V8,[2,28],{36:72,16:$Vi,37:$Vj,38:$Vk,39:$Vl,40:$Vm,41:$Vn,42:$Vo,43:$Vp}),o($Vq,[2,29]),o($Vq,[2,30]),o($Vq,[2,31]),o($Vq,[2,32]),o($Vq,[2,43],{28:$Vr,30:[1,73]}),o($Vs,[2,23]),{11:[1,75]},o($V8,[2,17]),o($V8,[2,19]),{11:[1,76]},o($V8,[2,10]),o($Va,[2,48]),o($Va,[2,45]),{17:[1,78],23:[1,77]},o($Vt,[2,53]),o($Vt,[2,49],{28:$Vr,30:[1,79]}),o($Vt,[2,50]),o($Vt,[2,51]),o($Vt,[2,52]),{11:$Vc,15:$Vd,27:48,28:$Ve,31:80,33:44,34:$Vf},o($Vu,[2,35]),o($Vu,[2,36]),o($Vu,[2,37]),o($Vu,[2,38]),o($Vu,[2,39]),o($Vu,[2,40]),o($Vu,[2,41]),o($Vu,[2,42]),{11:$Vc,15:$Vd,27:48,28:$Ve,31:81,33:44,34:$Vf},{15:[1,83],22:82,44:27},{11:[1,84]},{29:[1,85]},o($V2,[2,4]),o($Va,[2,46]),{11:$Vg,12:$V1,15:$Vd,19:62,27:59,28:$Ve,34:$Vh,46:86},{15:[1,87]},o($Vq,[2,34]),o($Vq,[2,33]),o($Vq,[2,44],{30:$V9}),o([14,16,17,28,30,37,38,39,40,41,42,43],$Vv,{21:$Vb}),{29:[1,88]},o($Vs,[2,24]),o($Vt,[2,54]),o([17,23,28,30],$Vv),o($Vs,[2,26])],
defaultActions: {5:[2,11],11:[2,2],14:[2,7],15:[2,8],22:[2,1]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new Error(str);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        function lex() {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0: /* skip whitespace */ 
break;
case 1: /* skip comments */ 
break;
case 2: return 'NEWLINE'; 
break;
case 3:
  yy_.yytext = yy_.yytext.substr(1, yy_.yyleng - 2);
  return 11

break;
case 4: return 40; 
break;
case 5: return 41; 
break;
case 6: return 42; 
break;
case 7: return 43; 
break;
case 8: return yy_.yytext; 
break;
case 9: return 8; 
break;
case 10: return 10; 
break;
case 11: return 34; 
break;
case 12: return 15; 
break;
case 13: return 6; 
break;
}
},
rules: [/^(?:\s+)/,/^(?:\/\/.*(\r|\n))/,/^(?:(\r?\n)+)/,/^(?:"[^\"]*"|'[^\']*')/,/^(?:==)/,/^(?:>=)/,/^(?:<=)/,/^(?:!=)/,/^(?:([(){}\[\]|:,.+*]))/,/^(?:import\b)/,/^(?:from\b)/,/^(?:(^(\d*\.?\d+)(?:e[+-]?\d+)?))/,/^(?:(^([$A-Za-z_\x7f-\uffff][$\w\x7f-\uffff]*)([^\n\S]*(?!))?))/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}